
// <auto-generated>
//  This code was generated by the following tool on 2024-07-01 17:38:51 GMT+02:00:
//      https://github.com/bottlenoselabs/c2cs (v0.0.0.0)
//
//  Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ReSharper disable All

#region Template
#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS8981
using Bindgen.Runtime;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

#endregion

public static unsafe partial class LumixWrapper
{
    private const string LibraryName = "lmxptpif.dll";

    #region API

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_AF_Config_Get_AF_Area_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_AF_Config_Get_AF_Area_Param(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_AF_Config_Get_AF_Mode_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_AF_Config_Get_AF_Mode_Param(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_AF_Config_Get_Capability")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_AF_Config_Get_Capability(LMX_STRUCT_AF_CONFIG_CAPA_INFO* pAF_Cfg_CapaInfo, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_AF_Config_Get_Quick_AF_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_AF_Config_Get_Quick_AF_Param(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_AF_Config_Set_AF_Area_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_AF_Config_Set_AF_Area_Param(int ulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_AF_Config_Set_AF_Mode_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_AF_Config_Set_AF_Mode_Param(int ulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_AF_Config_Set_Quick_AF_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_AF_Config_Set_Quick_AF_Param(int ulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Aperture_Get_Capability")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Aperture_Get_Capability(LMX_STRUCT_APERTURE_CAPA_INFO* pAperture_CapaInfo, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Aperture_Get_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Aperture_Get_Param(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Aperture_Get_RangeLimit")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Aperture_Get_RangeLimit(int* pulMinParam, int* pulMaxParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Aperture_Set_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Aperture_Set_Param(int ulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Aperture_Set_RangeLimit")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Aperture_Set_RangeLimit(int ulMinParam, int ulMaxParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_CameraMode_Get_Capability")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_CameraMode_Get_Capability(LMX_STRUCT_RECINFO_CAMERA_MODE_CAPA_INFO* pCameraMode_CapaInfo, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_CameraMode_Get_CreativeMode")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_CameraMode_Get_CreativeMode(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_CameraMode_Get_DriveMode")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_CameraMode_Get_DriveMode(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_CameraMode_Get_Mode_Pos")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_CameraMode_Get_Mode_Pos(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_CameraMode_Get_iA_Mode")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_CameraMode_Get_iA_Mode(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_CameraMode_Set_CreatvieMode")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_CameraMode_Set_CreatvieMode(int ulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_CameraMode_Set_DriveMode")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_CameraMode_Set_DriveMode(int ulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_CameraMode_Set_Mode_Pos")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_CameraMode_Set_Mode_Pos(int ulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_CameraMode_Set_iA_Mode")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_CameraMode_Set_iA_Mode(int ulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Close_Device")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Close_Device(int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Close_Session")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Close_Session(int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Ctrl_LiveView_Start")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Ctrl_LiveView_Start(int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Ctrl_LiveView_Stop")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Ctrl_LiveView_Stop(int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Delete_CallBackInfo")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Delete_CallBackInfo(int CallBackType);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Exposure_Get_Capability")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Exposure_Get_Capability(LMX_STRUCT_EXPOSURE_CAPA_INFO* pExposure_CapaInfo, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Exposure_Get_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Exposure_Get_Param(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Exposure_Get_RangeLimit")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Exposure_Get_RangeLimit(int* pulMinParam, int* pulMaxParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Exposure_Set_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Exposure_Set_Param(int ulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Exposure_Set_RangeLimit")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Exposure_Set_RangeLimit(int ulMinParam, int ulMaxParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Get_LiveView_data")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Get_LiveView_data(LMX_STRUCT_LIVEVIEW_INFO_HISTGRAM* pHistBuf, int* pHistSize, LMX_STRUCT_LIVEVIEW_INFO_POSTURE* pPostBuf, int* pPostSize, LMX_STRUCT_LIVEVIEW_INFO_LEVEL* pLevelBuf, int* pLevelSize, int* pJpegBuf, int* pJpegSize, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Get_Object")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Get_Object(int ObjectHandle, int* lpStoreBufAdder, int StoreBufSize, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Get_Object_DataSize")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Get_Object_DataSize(int ObjHandle, int* pDataSize, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Get_Object_FileName")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Get_Object_FileName(int ObjHandle, LMX_STRUCT_PTP_ARRAY_STRING* pFileName, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Get_Object_FormatType")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Get_Object_FormatType(int ObjHandle, int* pFormatType, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Get_Partial_Object")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Get_Partial_Object(int ObjectHandle, int* lpStoreBufAdder, int ui32_DataOffset, int u32_SplitTransferBytes, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Get_Partial_ObjectEx")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Get_Partial_ObjectEx(int ObjectHandle, int* lpStoreBufAdder, int ui64_DataOffset, int u32_SplitTransferBytes, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Get_PnPDeviceInfo")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Get_PnPDeviceInfo(PLMX_CONNECT_DEVICE_INFO plmxPnpDevInfo, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_ISO_Get_Capability")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_ISO_Get_Capability(LMX_STRUCT_ISO_CAPA_INFO* pIsoCapaInfo, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_ISO_Get_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_ISO_Get_Param(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_ISO_Get_UpperLimit")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_ISO_Get_UpperLimit(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_ISO_Set_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_ISO_Set_Param(int ulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_ISO_Set_UpperLimit")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_ISO_Set_UpperLimit(int ulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Init")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void LMX_func_api_Init();

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_LiveView_Str_Get_Recom_Img")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_LiveView_Str_Get_Recom_Img(LMX_STRUCT_LIVEVIEW_STR_RECOM_IMG* pRecomImg, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_LiveView_Str_Get_Trans_Img")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_LiveView_Str_Get_Trans_Img(LMX_STRUCT_LIVEVIEW_STR_TRANS_IMG* pTransImg, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_LiveView_Str_Set_Trans_Img")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_LiveView_Str_Set_Trans_Img(LMX_STRUCT_LIVEVIEW_STR_TRANS_IMG pTransImg, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Mov_Config_Get_C_Movie_mode_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Mov_Config_Get_C_Movie_mode_Param(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Mov_Config_Get_Capability")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Mov_Config_Get_Capability(LMX_STRUCT_MOV_MENU_CONFIG_CAPA_INFO* pMov_Cfg_CapaInfo, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Mov_Config_Get_HDMI_mode_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Mov_Config_Get_HDMI_mode_Param(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Mov_Config_Get_Quality_mode_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Mov_Config_Get_Quality_mode_Param(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Mov_Config_Get_Rec_mode_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Mov_Config_Get_Rec_mode_Param(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Mov_Config_Set_C_Movie_mode_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Mov_Config_Set_C_Movie_mode_Param(int ulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Mov_Config_Set_HDMI_mode_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Mov_Config_Set_HDMI_mode_Param(int ulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Mov_Config_Set_Quality_mode_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Mov_Config_Set_Quality_mode_Param(int ulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Mov_Config_Set_Rec_mode_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Mov_Config_Set_Rec_mode_Param(int ulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_MoveRec_Ctrl_Start")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_MoveRec_Ctrl_Start(int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_MoveRec_Ctrl_Stop")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_MoveRec_Ctrl_Stop(int stopmode, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Open_Session")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Open_Session(int ulConnectVer, int* pulDeviceConnectVer, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Rec_Ctrl_AF_AE")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Rec_Ctrl_AF_AE(LMX_STRUCT_REC_CTRL* lpRecCtrl, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Rec_Ctrl_Lens")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Rec_Ctrl_Lens(LMX_STRUCT_REC_CTRL* lpRecCtrl, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Rec_Ctrl_Release")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Rec_Ctrl_Release(LMX_STRUCT_REC_CTRL* lpRecCtrl, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Rec_Ctrl_Zoom")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Rec_Ctrl_Zoom(LMX_STRUCT_REC_CTRL* lpRecCtrl, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Reg_NotifyCallback")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Reg_NotifyCallback(int CallBackType, int appfunc);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_SS_Get_Capability")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_SS_Get_Capability(LMX_STRUCT_SS_CAPA_INFO* pSS_CapaInfo, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_SS_Get_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_SS_Get_Param(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_SS_Get_RangeLimit")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_SS_Get_RangeLimit(int* pulMinParam, int* pulMaxParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_SS_Set_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_SS_Set_Param(int ulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_SS_Set_RangeLimit")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_SS_Set_RangeLimit(int ulMinParam, int ulMaxParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Select_PnPDevice")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Select_PnPDevice(int dwDevIndex, PLMX_CONNECT_DEVICE_INFO plmxPnpDevInfo, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_SetupFilesConfig_Get_Target")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_SetupFilesConfig_Get_Target(int* punParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_SetupFilesConfig_Set_Target")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_SetupFilesConfig_Set_Target(int unParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_Skip_Object_Transfer")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_Skip_Object_Transfer(int ObjectHandle, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_WB_Get_ADJ_AB")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_WB_Get_ADJ_AB(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_WB_Get_ADJ_AB_Sep")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_WB_Get_ADJ_AB_Sep(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_WB_Get_ADJ_GM")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_WB_Get_ADJ_GM(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_WB_Get_Capability")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_WB_Get_Capability(LMX_STRUCT_WB_CAPA_INFO* pWB_CapaInfo, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_WB_Get_KSet")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_WB_Get_KSet(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_WB_Get_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_WB_Get_Param(int* pulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_WB_Set_ADJ_AB")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_WB_Set_ADJ_AB(int ulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_WB_Set_ADJ_AB_Sep")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_WB_Set_ADJ_AB_Sep(int ulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_WB_Set_ADJ_GM")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_WB_Set_ADJ_GM(int ulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_WB_Set_KSet")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_WB_Set_KSet(int ulParam, int* retError);

    [LibraryImport(LibraryName, EntryPoint = "LMX_func_api_WB_Set_Param")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int LMX_func_api_WB_Set_Param(int ulParam, int* retError);

    #endregion

    #region Types

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct _tag_LMX_CONNECT_DEVICE_INFO
    {

    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct _tag_LMX_STRUCT_AF_CONFIG_CAPA_INFO
    {

    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct _tag_LMX_STRUCT_APERTURE_CAPA_INFO
    {

    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct _tag_LMX_STRUCT_EXPOSURE_CAPA_INFO
    {

    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct _tag_LMX_STRUCT_ISO_CAPA_INFO
    {

    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct _tag_LMX_STRUCT_LIVEVIEW_INFO_HISTGRAM
    {

    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct _tag_LMX_STRUCT_LIVEVIEW_INFO_LEVEL
    {

    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct _tag_LMX_STRUCT_LIVEVIEW_INFO_POSTURE
    {

    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct _tag_LMX_STRUCT_LIVEVIEW_STR_RECOM_IMG
    {

    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct _tag_LMX_STRUCT_LIVEVIEW_STR_TRANS_IMG
    {

    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct _tag_LMX_STRUCT_MOV_MENU_CONFIG_CAPA_INFO
    {

    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct _tag_LMX_STRUCT_PTP_ARRAY_STRING
    {

    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct _tag_LMX_STRUCT_RECINFO_CAMERA_MODE_CAPA_INFO
    {

    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct _tag_LMX_STRUCT_REC_CTRL
    {

    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct _tag_LMX_STRUCT_SS_CAPA_INFO
    {

    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct _tag_LMX_STRUCT_WB_CAPA_INFO
    {

    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct LMX_STRUCT_AF_CONFIG_CAPA_INFO
    {
        [FieldOffset(0)]
        public _tag_LMX_STRUCT_AF_CONFIG_CAPA_INFO Data;

        public static implicit operator _tag_LMX_STRUCT_AF_CONFIG_CAPA_INFO(LMX_STRUCT_AF_CONFIG_CAPA_INFO data) => data.Data;
        public static implicit operator LMX_STRUCT_AF_CONFIG_CAPA_INFO(_tag_LMX_STRUCT_AF_CONFIG_CAPA_INFO data) => new LMX_STRUCT_AF_CONFIG_CAPA_INFO() { Data = data };
    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct LMX_STRUCT_APERTURE_CAPA_INFO
    {
        [FieldOffset(0)]
        public _tag_LMX_STRUCT_APERTURE_CAPA_INFO Data;

        public static implicit operator _tag_LMX_STRUCT_APERTURE_CAPA_INFO(LMX_STRUCT_APERTURE_CAPA_INFO data) => data.Data;
        public static implicit operator LMX_STRUCT_APERTURE_CAPA_INFO(_tag_LMX_STRUCT_APERTURE_CAPA_INFO data) => new LMX_STRUCT_APERTURE_CAPA_INFO() { Data = data };
    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct LMX_STRUCT_EXPOSURE_CAPA_INFO
    {
        [FieldOffset(0)]
        public _tag_LMX_STRUCT_EXPOSURE_CAPA_INFO Data;

        public static implicit operator _tag_LMX_STRUCT_EXPOSURE_CAPA_INFO(LMX_STRUCT_EXPOSURE_CAPA_INFO data) => data.Data;
        public static implicit operator LMX_STRUCT_EXPOSURE_CAPA_INFO(_tag_LMX_STRUCT_EXPOSURE_CAPA_INFO data) => new LMX_STRUCT_EXPOSURE_CAPA_INFO() { Data = data };
    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct LMX_STRUCT_ISO_CAPA_INFO
    {
        [FieldOffset(0)]
        public _tag_LMX_STRUCT_ISO_CAPA_INFO Data;

        public static implicit operator _tag_LMX_STRUCT_ISO_CAPA_INFO(LMX_STRUCT_ISO_CAPA_INFO data) => data.Data;
        public static implicit operator LMX_STRUCT_ISO_CAPA_INFO(_tag_LMX_STRUCT_ISO_CAPA_INFO data) => new LMX_STRUCT_ISO_CAPA_INFO() { Data = data };
    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct LMX_STRUCT_LIVEVIEW_INFO_HISTGRAM
    {
        [FieldOffset(0)]
        public _tag_LMX_STRUCT_LIVEVIEW_INFO_HISTGRAM Data;

        public static implicit operator _tag_LMX_STRUCT_LIVEVIEW_INFO_HISTGRAM(LMX_STRUCT_LIVEVIEW_INFO_HISTGRAM data) => data.Data;
        public static implicit operator LMX_STRUCT_LIVEVIEW_INFO_HISTGRAM(_tag_LMX_STRUCT_LIVEVIEW_INFO_HISTGRAM data) => new LMX_STRUCT_LIVEVIEW_INFO_HISTGRAM() { Data = data };
    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct LMX_STRUCT_LIVEVIEW_INFO_LEVEL
    {
        [FieldOffset(0)]
        public _tag_LMX_STRUCT_LIVEVIEW_INFO_LEVEL Data;

        public static implicit operator _tag_LMX_STRUCT_LIVEVIEW_INFO_LEVEL(LMX_STRUCT_LIVEVIEW_INFO_LEVEL data) => data.Data;
        public static implicit operator LMX_STRUCT_LIVEVIEW_INFO_LEVEL(_tag_LMX_STRUCT_LIVEVIEW_INFO_LEVEL data) => new LMX_STRUCT_LIVEVIEW_INFO_LEVEL() { Data = data };
    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct LMX_STRUCT_LIVEVIEW_INFO_POSTURE
    {
        [FieldOffset(0)]
        public _tag_LMX_STRUCT_LIVEVIEW_INFO_POSTURE Data;

        public static implicit operator _tag_LMX_STRUCT_LIVEVIEW_INFO_POSTURE(LMX_STRUCT_LIVEVIEW_INFO_POSTURE data) => data.Data;
        public static implicit operator LMX_STRUCT_LIVEVIEW_INFO_POSTURE(_tag_LMX_STRUCT_LIVEVIEW_INFO_POSTURE data) => new LMX_STRUCT_LIVEVIEW_INFO_POSTURE() { Data = data };
    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct LMX_STRUCT_LIVEVIEW_STR_RECOM_IMG
    {
        [FieldOffset(0)]
        public _tag_LMX_STRUCT_LIVEVIEW_STR_RECOM_IMG Data;

        public static implicit operator _tag_LMX_STRUCT_LIVEVIEW_STR_RECOM_IMG(LMX_STRUCT_LIVEVIEW_STR_RECOM_IMG data) => data.Data;
        public static implicit operator LMX_STRUCT_LIVEVIEW_STR_RECOM_IMG(_tag_LMX_STRUCT_LIVEVIEW_STR_RECOM_IMG data) => new LMX_STRUCT_LIVEVIEW_STR_RECOM_IMG() { Data = data };
    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct LMX_STRUCT_LIVEVIEW_STR_TRANS_IMG
    {
        [FieldOffset(0)]
        public _tag_LMX_STRUCT_LIVEVIEW_STR_TRANS_IMG Data;

        public static implicit operator _tag_LMX_STRUCT_LIVEVIEW_STR_TRANS_IMG(LMX_STRUCT_LIVEVIEW_STR_TRANS_IMG data) => data.Data;
        public static implicit operator LMX_STRUCT_LIVEVIEW_STR_TRANS_IMG(_tag_LMX_STRUCT_LIVEVIEW_STR_TRANS_IMG data) => new LMX_STRUCT_LIVEVIEW_STR_TRANS_IMG() { Data = data };
    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct LMX_STRUCT_MOV_MENU_CONFIG_CAPA_INFO
    {
        [FieldOffset(0)]
        public _tag_LMX_STRUCT_MOV_MENU_CONFIG_CAPA_INFO Data;

        public static implicit operator _tag_LMX_STRUCT_MOV_MENU_CONFIG_CAPA_INFO(LMX_STRUCT_MOV_MENU_CONFIG_CAPA_INFO data) => data.Data;
        public static implicit operator LMX_STRUCT_MOV_MENU_CONFIG_CAPA_INFO(_tag_LMX_STRUCT_MOV_MENU_CONFIG_CAPA_INFO data) => new LMX_STRUCT_MOV_MENU_CONFIG_CAPA_INFO() { Data = data };
    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct LMX_STRUCT_PTP_ARRAY_STRING
    {
        [FieldOffset(0)]
        public _tag_LMX_STRUCT_PTP_ARRAY_STRING Data;

        public static implicit operator _tag_LMX_STRUCT_PTP_ARRAY_STRING(LMX_STRUCT_PTP_ARRAY_STRING data) => data.Data;
        public static implicit operator LMX_STRUCT_PTP_ARRAY_STRING(_tag_LMX_STRUCT_PTP_ARRAY_STRING data) => new LMX_STRUCT_PTP_ARRAY_STRING() { Data = data };
    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct LMX_STRUCT_RECINFO_CAMERA_MODE_CAPA_INFO
    {
        [FieldOffset(0)]
        public _tag_LMX_STRUCT_RECINFO_CAMERA_MODE_CAPA_INFO Data;

        public static implicit operator _tag_LMX_STRUCT_RECINFO_CAMERA_MODE_CAPA_INFO(LMX_STRUCT_RECINFO_CAMERA_MODE_CAPA_INFO data) => data.Data;
        public static implicit operator LMX_STRUCT_RECINFO_CAMERA_MODE_CAPA_INFO(_tag_LMX_STRUCT_RECINFO_CAMERA_MODE_CAPA_INFO data) => new LMX_STRUCT_RECINFO_CAMERA_MODE_CAPA_INFO() { Data = data };
    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct LMX_STRUCT_REC_CTRL
    {
        [FieldOffset(0)]
        public _tag_LMX_STRUCT_REC_CTRL Data;

        public static implicit operator _tag_LMX_STRUCT_REC_CTRL(LMX_STRUCT_REC_CTRL data) => data.Data;
        public static implicit operator LMX_STRUCT_REC_CTRL(_tag_LMX_STRUCT_REC_CTRL data) => new LMX_STRUCT_REC_CTRL() { Data = data };
    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct LMX_STRUCT_SS_CAPA_INFO
    {
        [FieldOffset(0)]
        public _tag_LMX_STRUCT_SS_CAPA_INFO Data;

        public static implicit operator _tag_LMX_STRUCT_SS_CAPA_INFO(LMX_STRUCT_SS_CAPA_INFO data) => data.Data;
        public static implicit operator LMX_STRUCT_SS_CAPA_INFO(_tag_LMX_STRUCT_SS_CAPA_INFO data) => new LMX_STRUCT_SS_CAPA_INFO() { Data = data };
    }

    [StructLayout(LayoutKind.Explicit, Size = 1, Pack = 1)]
    public struct LMX_STRUCT_WB_CAPA_INFO
    {
        [FieldOffset(0)]
        public _tag_LMX_STRUCT_WB_CAPA_INFO Data;

        public static implicit operator _tag_LMX_STRUCT_WB_CAPA_INFO(LMX_STRUCT_WB_CAPA_INFO data) => data.Data;
        public static implicit operator LMX_STRUCT_WB_CAPA_INFO(_tag_LMX_STRUCT_WB_CAPA_INFO data) => new LMX_STRUCT_WB_CAPA_INFO() { Data = data };
    }

    [StructLayout(LayoutKind.Explicit, Size = 8, Pack = 8)]
    public struct PLMX_CONNECT_DEVICE_INFO
    {
        [FieldOffset(0)]
        public _tag_LMX_CONNECT_DEVICE_INFO* Data;

        public static implicit operator _tag_LMX_CONNECT_DEVICE_INFO*(PLMX_CONNECT_DEVICE_INFO data) => data.Data;
        public static implicit operator PLMX_CONNECT_DEVICE_INFO(_tag_LMX_CONNECT_DEVICE_INFO* data) => new PLMX_CONNECT_DEVICE_INFO() { Data = data };
    }

    public const int DEVINFO_DEF_ARRAY_MAX = 512;

    public const int DEVINFO_DEF_STRING_MAX = 256;

    public const int LMX_BOOL_FALSE = 0;

    public const int LMX_BOOL_TRUE = 1;

    public const int LMX_DEF_LIVEVIEW_HISTGRAM_ELEMENT_SIZE = 64;

    public const int LMX_DEF_LIVEVIEW_STREAMDATA_SIZE_MAX = 1048576;

    public const int LMX_DEF_OBJ_CARDLESS_TRNSFER_HDL = 305419896;

    public const int LMX_DEF_USER_PTP_ARRAY_MAX = 512;

    public const int LMX_DEF_USER_PTP_STRING_MAX = 256;

    #endregion
}
